### ISSUE TITLE
Basic install not working 

### ISSUE THREAD

**Issue by ezmiller** [SanderSpies/react-material#78]
Hi, I wanted to look at what you've done here, but currently your webpack install seems to be broken: 
```
Version: webpack 1.5.3
Time: 11354ms
         Asset     Size  Chunks             Chunk Names
     bundle.js   786150       0  [emitted]  main
    bundle.css      311       0  [emitted]  main
 bundle.js.map  1195935       0  [emitted]  main
bundle.css.map       87       0  [emitted]  main
   [0] multi main 40 {0} [built] [1 error]
    + 197 hidden modules

ERROR in ./~/react-style/lib/index.js
Module build failed: AssertionError: className is expected to be a string
    at Console.assert (console.js:102:23)
    at generateCSSClassName (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/generateUniqueCSSClassName.js:20:11)
    at Context.recast.visit.getStyleName (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotateStyleName.js:71:23)
    at Context.recast.visit.visitCallExpression (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotateStyleName.js:24:50)
    at Context.invokeVisitorMethod (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:206:43)
    at Visitor.PVp.visit (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:108:21)
    at visitChildren (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:136:21)
    at Visitor.PVp.visit (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:116:9)
    at visitChildren (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:136:21)
    at Visitor.PVp.visit (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:116:9)
 @ ./views/DocumentationApplication.js 9:17-39

ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/react-style-webpack-plugin/lib/entry.js!./views/DocumentationApplication.js
Module build failed: Error: Cannot find module "react-style"
    at webpackMissingModule (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:1:0)
    at Object.module.exports.Colors.red.P50 (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:1:0)
    at __webpack_require__ (webpack/bootstrap 990e88fce7f3b470980e:19:0)
webpack/bootstrap 990e88fce7f3b470980e:41:0    at /Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:43:18
    at Object.<anonymous> (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:46:10)
    at Module._compile (/Users/ethan/Sites/learning/react-examples/react-material/style/Colors.js:144:19)
    at Object.loaderContext.exec (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:37:0)
    at Object.<anonymous> (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:68:0)
    at Tapable.<anonymous> (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/entry.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotate.js!/Users/ethan/Sites/learning/react-examples/react-material/node_modules/jsx-loader/index.js?harmony&sourceMap!/Users/ethan/Sites/learning/react-examples/react-material/views/DocumentationApplication.js:161:0)
/Users/ethan/Sites/learning/react-examples/react-material/style/Colors.js:86:10    at /Users/ethan/Sites/learning/react-examples/react-material/node_modules/webpack/lib/Compiler.js:398:12
 @ multi main
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 196 hidden modules

    ERROR in ./~/react-style/lib/index.js
    Module build failed: AssertionError: className is expected to be a string
        at Console.assert (console.js:102:23)
        at generateCSSClassName (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/generateUniqueCSSClassName.js:20:11)
        at Context.recast.visit.getStyleName (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotateStyleName.js:71:23)
        at Context.recast.visit.visitCallExpression (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/lib/annotateStyleName.js:24:50)
        at Context.invokeVisitorMethod (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:206:43)
        at Visitor.PVp.visit (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:108:21)
        at visitChildren (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:136:21)
        at Visitor.PVp.visit (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:116:9)
        at visitChildren (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:136:21)
        at Visitor.PVp.visit (/Users/ethan/Sites/learning/react-examples/react-material/node_modules/react-style-webpack-plugin/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:116:9)
     @ ./~/react-style-webpack-plugin/lib/entry.js!./~/react-style-webpack-plugin/lib/annotate.js!./~/jsx-loader?harmony&sourceMap!./views/DocumentationApplication.js 1:19-41 10:17-39
```

**Comment by TimothyKrell** [comment]
I'm seeing this error too. After messing around for ~10 minutes I haven't figured out the problem. I'll see if I can figure something out tomorrow.

**Comment by TimothyKrell** [comment]
The main work is happening on the 0.13 branch. Try using that. I had to just edit `components/Application.js` to include React and react-style to get things working.

**Comment by BerkeleyTrue** [comment]
@ezmiller I am going to close this for now as the main branch(0.13) is working. If you cannot get that branch to work please feel free to re-open.
